services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.devcontainer
    volumes:
      - ./:/repo
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.devcontainer
    volumes:
      - ./:/repo
    ports:
      - "3000:3000"
    tty: true
