FROM node:20-slim 
RUN corepack enable

WORKDIR /repo/frontend
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml ./frontend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY ./ /repo
CMD pnpm run dev